### ISSUE TITLE
how can i use

### ISSUE THREAD

**Issue by lpzahd** [HollowHorizon/KotlinScriptForForge#2]

**Comment by HollowHorizon** [comment]
I recommend seeing how I implemented this in my other [mod](https://github.com/HollowHorizon/HollowEngine/blob/1.19.2/src/main/java/ru/hollowhorizon/hollowengine/common/scripting/content/ContentScript.kt), and also check out the official [KotlinScript documentation](https://kotlinlang.org/docs/custom-script-deps-tutorial.html).
The mod itself allows you to execute any Kotlin scripts by directly accessing the code of the game or other mods, in addition, this system bypasses obfuscation, which allows you to write scripts using standard mappings right in the game.
